import { useEffect, useState } from 'react'
import { createRoot } from 'react-dom/client'
import './styles.css'

type Status = 'not-started' | 'in-progress' | 'completed'
type Node = { id: string; name: string; icon?: string; parentId: string | null; status: Status }
const key = 'learning-tracker-nodes'
const icons = ['◌', '🐍', '▦', '◈', '⚡', '◆', '◇', '✦', '◎', '⌘', '☷', '↗']
const id = () => `${Date.now()}-${Math.random().toString(36).slice(2)}`
const initial: Node[] = []
function leaves(nodes: Node[], node: Node): Node[] { const children = nodes.filter(item => item.parentId === node.id); return children.length ? children.flatMap(child => leaves(nodes, child)) : [node] }
function percentage(nodes: Node[], node: Node) { const items = leaves(nodes, node); return items.length ? Math.round(items.filter(item => item.status === 'completed').length / items.length * 100) : 0 }
function displayStatus(nodes: Node[], node: Node): Status { const children = nodes.some(item => item.parentId === node.id); if (!children) return node.status; const value = percentage(nodes, node); return value === 100 ? 'completed' : value > 0 ? 'in-progress' : 'not-started' }
function App() {
  const [nodes, setNodes] = useState<Node[]>(() => { try { return JSON.parse(localStorage.getItem(key) || '[]') } catch { return initial } })
  const [expanded, setExpanded] = useState<Set<string>>(new Set())
  const [selected, setSelected] = useState<string | null>(null)
  const [modal, setModal] = useState<{ parentId: string | null; defaultName?: string } | null>(null)
  useEffect(() => localStorage.setItem(key, JSON.stringify(nodes)), [nodes])
  const add = (name: string, icon: string, parentId: string | null) => { const item = { id: id(), name, icon, parentId, status: 'not-started' as Status }; setNodes(current => [...current, item]); if (parentId) setExpanded(current => new Set(current).add(parentId)); setModal(null) }
  const remove = (nodeId: string) => { setNodes(current => current.filter(item => item.id !== nodeId && item.parentId !== nodeId)); setSelected(null) }
  const roots = nodes.filter(node => node.parentId === null)
  return <div className="app"><aside><div className="brand">↗ <span>Learning<br/><b>Tracker</b></span></div><nav><button className="active">⌂ Dashboard</button><button>▤ My learning</button><button>◒ Progress</button><button>⚙ Settings</button></nav><div className="side-title">MY LEARNING <button onClick={() => setModal({ parentId: null })}>+</button></div>{roots.map(root => <div className="side-root" key={root.id}><span>{root.icon || '◌'} {root.name}</span><b>{percentage(nodes, root)}%</b></div>)}</aside><main><header><span>⌕ Search your learning...</span><button>☾</button></header><section className="heading"><div><small>YOUR WORKSPACE</small><h1>Welcome back, learner.</h1><p>Build momentum, one idea at a time.</p></div><button className="primary" onClick={() => setModal({ parentId: null })}>+ Add learning</button></section><div className="stats"><Stat label="Total items" value={nodes.length}/><Stat label="Completed" value={nodes.filter(node => node.status === 'completed').length}/><Stat label="In progress" value={nodes.filter(node => node.status === 'in-progress').length}/><Stat label="Overall progress" value={roots.length ? `${Math.round(roots.reduce((total, root) => total + percentage(nodes, root), 0) / roots.length)}%` : '0%'}/></div><div className="section-head"><div><small>THE KNOWLEDGE MAP</small><h2>My learning</h2></div></div><div className="tree">{roots.length ? roots.map(root => <Tree key={root.id} node={root} depth={0} nodes={nodes} expanded={expanded} setExpanded={setExpanded} selected={selected} setSelected={setSelected} addChild={parentId => setModal({ parentId })} changeStatus={nodeId => setNodes(current => current.map(item => item.id === nodeId ? {...item, status: item.status === 'not-started' ? 'in-progress' : item.status === 'in-progress' ? 'completed' : 'not-started'} : item))} remove={remove}/>) : <div className="empty"><h2>Start your learning journey</h2><p>Add a main learning item, then use Add child to build your hierarchy.</p><button className="primary" onClick={() => setModal({ parentId: null })}>+ Add your first item</button></div>}</div></main>{modal && <AddModal defaultName={modal.defaultName} close={() => setModal(null)} create={(name, icon) => add(name, icon, modal.parentId)} />}</div>
}
function Stat({ label, value }: { label: string; value: string | number }) { return <div className="stat"><small>{label}</small><strong>{value}</strong></div> }
function Tree({ node, depth, nodes, expanded, setExpanded, selected, setSelected, addChild, changeStatus, remove }: { node: Node; depth: number; nodes: Node[]; expanded: Set<string>; setExpanded: (value: Set<string>) => void; selected: string | null; setSelected: (value: string) => void; addChild: (id: string) => void; changeStatus: (id: string) => void; remove: (id: string) => void }) { const children = nodes.filter(item => item.parentId === node.id); const open = expanded.has(node.id); const status = displayStatus(nodes, node); const addLabel = depth === 0 ? '+ Add child' : '+ Add subchild'; return <div className="tree-node"><div className={selected === node.id ? 'row selected' : 'row'} onClick={() => setSelected(node.id)}><button className="arrow" onClick={event => { event.stopPropagation(); if (children.length) { const next = new Set(expanded); next.has(node.id) ? next.delete(node.id) : next.add(node.id); setExpanded(next) } }}>{children.length ? open ? '⌄' : '›' : '·'}</button><span className="node-icon">{node.icon || '◌'}</span><div className="node-name"><b>{node.name}</b><small>{children.length ? `${children.length} item${children.length === 1 ? '' : 's'}` : 'Learning item'}</small></div><div className="bar"><i style={{ width: `${percentage(nodes, node)}%` }}/></div><strong className="percent">{percentage(nodes, node)}%</strong><button className={`status ${status}`} onClick={event => { event.stopPropagation(); if (!children.length) changeStatus(node.id) }}>{status === 'completed' ? '✓' : status === 'in-progress' ? '◔' : '○'}</button><button className="dots" onClick={event => { event.stopPropagation(); if (confirm(`Delete ${node.name} and its children?`)) remove(node.id) }}>•••</button></div>{open && <div className="children">{children.map(child => <Tree key={child.id} node={child} depth={depth + 1} nodes={nodes} expanded={expanded} setExpanded={setExpanded} selected={selected} setSelected={setSelected} addChild={addChild} changeStatus={changeStatus} remove={remove}/>)}<button className="add-child" onClick={() => addChild(node.id)}>{addLabel}</button></div>}{!open && <button className="add-child collapsed" onClick={() => addChild(node.id)}>{addLabel}</button>}</div> }
function AddModal({ close, create, defaultName }: { close: () => void; create: (name: string, icon: string) => void; defaultName?: string }) { const [name, setName] = useState(defaultName || ''); const [icon, setIcon] = useState('◌'); const [showIcons, setShowIcons] = useState(false); return <div className="backdrop"><div className="modal"><button className="close" onClick={close}>×</button><small>NEW LEARNING ITEM</small><h2>Add to your map</h2><label>Name<input autoFocus value={name} onChange={event => setName(event.target.value)} placeholder="e.g. Python"/></label><label>Icon<button type="button" className="icon-input" onClick={() => setShowIcons(open => !open)}>{icon}<span>　{showIcons ? 'Hide icons' : 'Choose an icon'}</span><b>{showIcons ? '⌃' : '⌄'}</b></button>{showIcons && <div className="icon-picker">{icons.map(option => <button type="button" key={option} className={icon === option ? 'icon-choice selected' : 'icon-choice'} onClick={() => setIcon(option)}>{option}</button>)}</div>}</label><div className="actions"><button onClick={close}>Cancel</button><button className="primary" disabled={!name.trim()} onClick={() => create(name.trim(), icon)}>Create item</button></div></div></div> }
createRoot(document.getElementById('root')!).render(<App />)
